### ISSUE TITLE
Example notebook?

### ISSUE THREAD

**Issue by haesleinhuepf** [jni/explode-view#1]
Hey Juan @jni ,

I'm considering GPU-accelerating the code here. However, can you provide an example notebook that shows how to use it?

Thanks!
Robert

**Comment by haesleinhuepf** [comment]
Will you use dask and napari to go back and forth through the explosion? (-:

**Comment by haesleinhuepf** [comment]
Found the answer:
https://github.com/damiandn/scripts

I show myself out 😉

**Comment by jni** [comment]
@haesleinhuepf that script is "outdated" compared to the code here. I'm reopening this. =)
